### ISSUE TITLE
Captions don't match the page. 

### ISSUE THREAD

**Issue by Floxtor** [uscki/appcki#11]
The captions don't match the contens of the pages:
Agenda displays news items. 
Nieuws is empty.
Vergaderplanner displays the poll.
Poll displays the agenda.

Fun fact on my MacBook Nieuws displays the Vergaderplanner instead of nothing.

**Comment by Ilsontfous** [comment]
Fun fact: this is correct. I'm working on getting the settings menu to a side view, and I had the titles change fixed through a hack already, but that sort of stopped working but is low priority.

Other fun fact: it showed a blank page on your not-macbook because that page should be showing the meeting planner which didn't work on the latter

**Comment by Ilsontfous** [comment]
Bug #3 blijft staan
